config/routes.rb
Rails.application.routes.draw do

  root "uploader#index"

  get "/uploader", to: "uploader#index"
  post "/upload", to: "uploader#upload"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/uploader.rb
class Uploader < ApplicationRecord


    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            record = Uploader.new
            record.name = row[0]
            record.date = row[1]
            record.number = row[2]
            record.description = row[3]
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/uploader_controller.rb
class UploaderController < ApplicationController
  
  
  def index
    @uploader = Uploader.new
  end

  def upload

    puts params[:file]
    #Uploader.import(params[:file])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploader_helper.rb
module UploaderHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>RorBoomering</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= yield %>

  </body>

</html>

app/views/uploader/index.html.erb
<h1>Uploader</h1>

<%= form_for @uploader, url: upload_path do |f| %>
   <div class="form-group">
      <%= f.label :file, "Upload CSV File" %>
      <%= f.file_field :file, class: 'form-control-file', required: true %>
   </div>
   <%= f.button :submit, value: "Upload CSV", class: "btn btn-primary" %>
<% end %>